name: JIRA consistency

on: 
  issues:
    types: ['milestoned', 'demilestoned']
  pull_request:
    types: ['opened', 'edited', 'synchronize', 'reopened', 'closed']
  schedule:
    - cron: '5 * * * *'

jobs:
  jira_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: cchantep/probot-jira@ghaction-1.0.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_TOKEN_VALUE: 'personal_token'
          PERSONAL_TOKEN_USER: ${{ secrets.PERSONAL_TOKEN_VALUE }}
          JIRA_API_TOKEN: 78dc867c80bd52b86f9e73f6f5aa98558fed006c
          JIRA_DOMAIN: 'acosta-it.atlassian.net'
          JIRA_USER: 'gaurang.shah@mosaic.com'
          JIRA_PROJECT_NAME: 'DPMA'
